//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSQL.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartSQL.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;7z&quot;:{&quot;n&quot;:&quot;7z&quot;,&quot;p&quot;:&quot;/7z&quot;,&quot;d&quot;:&quot;拥有极高压缩比的开源压缩软件。&quot;},&quot;ab&quot;:{&quot;n&quot;:&quot;ab&quot;,&quot;p&quot;:&quot;/ab&quot;,&quot;d&quot;:&quot;Apache服务器的性能测试工具&quot;},&quot;accept&quot;:{&quot;n&quot;:&quot;accept&quot;,&quot;p&quot;:&quot;/accept&quot;,&quot;d&quot;:&quot;指示打印系统接受发往指定目标打印机的打印任务&quot;},&quot;ack&quot;:{&quot;n&quot;:&quot;ack&quot;,&quot;p&quot;:&quot;/ack&quot;,&quot;d&quot;:&quot;比grep好用的文本搜索工具&quot;},&quot;ag&quot;:{&quot;n&quot;:&quot;ag&quot;,&quot;p&quot;:&quot;/ag&quot;,&quot;d&quot;:&quot;ack 的升级版，C语言编写，更快更人性化&quot;},&quot;alias&quot;:{&quot;n&quot;:&quot;alias&quot;,&quot;p&quot;:&quot;/alias&quot;,&quot;d&quot;:&quot;定义或显示别名。&quot;},&quot;apachectl&quot;:{&quot;n&quot;:&quot;apachectl&quot;,&quot;p&quot;:&quot;/apachectl&quot;,&quot;d&quot;:&quot;Apache服务器前端控制工具&quot;},&quot;apk&quot;:{&quot;n&quot;:&quot;apk&quot;,&quot;p&quot;:&quot;/apk&quot;,&quot;d&quot;:&quot;Alpine Linux 下的包管理工具&quot;},&quot;apropos&quo... 的本地化字符串。
        /// </summary>
        internal static string linux {
            get {
                return ResourceManager.GetString("linux", resourceCulture);
            }
        }
    }
}
